import { Config } from '../core/Config'
import { AvatarLayerStack } from './AvatarLayerStack'
import {
  palettes__000__transparent,
  palettes__001__themes,
  palettes__002__humanoid_human,
  palettes__003__hair,
  palettes__004__jewelry,
  palettes__005__eyes,
  palettes__006__glasses_solid_with_clear_lenses,
  palettes__007__space_suit,
  palettes__008__sunshield,
  palettes__009__vr,
  palettes__010__vr_rainbow,
  palettes__011__sunglasses,
  palettes__012__glasses_3d,
  palettes__013__glasses_tortoiseshell,
  palettes__014__medical_mask,
  palettes__015__makeup,
  palettes__016__belts,
} from './PaletteConfig'

export const AvatarConfig: Config = {
  [AvatarLayerStack.body.name]: {
    layer: AvatarLayerStack.body,
    patterns: {
      'pattern:invisible': palettes__000__transparent,
      'pattern:bare_chest': palettes__002__humanoid_human,
      'pattern:inner_chest': palettes__002__humanoid_human,
      'pattern:broad_chest': palettes__002__humanoid_human,
      'pattern:nipples_masculine': palettes__002__humanoid_human,
      'pattern:nipples_feminine': palettes__002__humanoid_human,
      'pattern:small_breasts': palettes__002__humanoid_human,
      'pattern:breasts': palettes__002__humanoid_human,
      'pattern:large_breasts': palettes__002__humanoid_human,
      // 'pattern:rainbow': palettes__019__rainbow,
    },
  },
  [AvatarLayerStack.bottomwear.name]: {
    layer: AvatarLayerStack.bottomwear,
    patterns: {
      'pattern:naked': palettes__000__transparent,
      'pattern:pants_solid1': palettes__001__themes,
      'pattern:pants_solid2': palettes__001__themes,
      'pattern:pants_solid3': palettes__001__themes,
      'pattern:pants_solid4': palettes__001__themes,
      'pattern:pants_solid5': palettes__001__themes,
      'pattern:pants_solid6': palettes__001__themes,
      'pattern:pants_solid7': palettes__001__themes,
      'pattern:pants_gradient1': palettes__001__themes,
      'pattern:pants_gradient2': palettes__001__themes,
      'pattern:pants_gradient3': palettes__001__themes,
      'pattern:pants_gradient4': palettes__001__themes,
      'pattern:pants_gradient5': palettes__001__themes,
      'pattern:pants_speckled1': palettes__001__themes,
      'pattern:pants_speckled2': palettes__001__themes,
      'pattern:pants_speckled3': palettes__001__themes,
      'pattern:pants_speckled4': palettes__001__themes,
      'pattern:shorts_solid1': palettes__001__themes,
      'pattern:shorts_solid2': palettes__001__themes,
      'pattern:shorts_solid3': palettes__001__themes,
      'pattern:shorts_solid4': palettes__001__themes,
      'pattern:shorts_solid5': palettes__001__themes,
      'pattern:shorts_solid6': palettes__001__themes,
      'pattern:shorts_solid7': palettes__001__themes,
      'pattern:shorts_gradient1': palettes__001__themes,
      'pattern:shorts_gradient2': palettes__001__themes,
      'pattern:shorts_gradient3': palettes__001__themes,
      'pattern:shorts_gradient4': palettes__001__themes,
      'pattern:shorts_speckled1': palettes__001__themes,
      'pattern:shorts_speckled2': palettes__001__themes,
      'pattern:shorts_speckled3': palettes__001__themes,
      'pattern:shorts_speckled4': palettes__001__themes,
      'pattern:underwear_solid1': palettes__001__themes,
      'pattern:underwear_solid2': palettes__001__themes,
      'pattern:underwear_solid3': palettes__001__themes,
      'pattern:underwear_solid4': palettes__001__themes,
      'pattern:underwear_solid5': palettes__001__themes,
      'pattern:underwear_solid6': palettes__001__themes,
      'pattern:underwear_solid7': palettes__001__themes,
      'pattern:skirt_solid1': palettes__001__themes,
      'pattern:skirt_solid2': palettes__001__themes,
      'pattern:skirt_solid3': palettes__001__themes,
      'pattern:skirt_solid4': palettes__001__themes,
      'pattern:skirt_solid5': palettes__001__themes,
      'pattern:skirt_solid6': palettes__001__themes,
      'pattern:skirt_solid7': palettes__001__themes,
      'pattern:skirt_gradient1': palettes__001__themes,
      'pattern:skirt_gradient2': palettes__001__themes,
      'pattern:skirt_gradient3': palettes__001__themes,
      'pattern:skirt_gradient4': palettes__001__themes,
      'pattern:skirt_gradient5': palettes__001__themes,
      'pattern:skirt_radial_gradient1': palettes__001__themes,
      'pattern:skirt_radial_gradient2': palettes__001__themes,
      'pattern:skirt_radial_gradient3': palettes__001__themes,
      'pattern:skirt_radial_gradient4': palettes__001__themes,
      'pattern:skirt_radial_gradient5': palettes__001__themes,
      'pattern:space_suit': palettes__007__space_suit,
      'pattern:space_shorts': palettes__007__space_suit,
    },
  },
  [AvatarLayerStack.facewear.name]: {
    layer: AvatarLayerStack.facewear,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:medical_mask': palettes__014__medical_mask,
    },
  },
  [AvatarLayerStack.facial_hair.name]: {
    layer: AvatarLayerStack.facial_hair,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:mustache': palettes__003__hair,
      'pattern:handlebar_mustache': palettes__003__hair,
      'pattern:goatee': palettes__003__hair,
      'pattern:chin_puff': palettes__003__hair,
      'pattern:chinstrap_thin': palettes__003__hair,
      'pattern:chinstrap': palettes__003__hair,
      'pattern:muttonchops': palettes__003__hair,
      'pattern:neckbeard': palettes__003__hair,
      'pattern:beard': palettes__003__hair,
      'pattern:full_beard': palettes__003__hair,
      'pattern:bushy_beard': palettes__003__hair,
    },
  },
  [AvatarLayerStack.footwear.name]: {
    layer: AvatarLayerStack.footwear,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:shoes1': palettes__001__themes,
      'pattern:shoes2': palettes__001__themes,
      'pattern:shoes3': palettes__001__themes,
      'pattern:shoes4': palettes__001__themes,
      'pattern:shoes5': palettes__001__themes,
      'pattern:shoes6': palettes__001__themes,
      'pattern:shoes7': palettes__001__themes,
    },
  },
  [AvatarLayerStack.jewelry.name]: {
    layer: AvatarLayerStack.jewelry,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:earrings': palettes__004__jewelry,
      'pattern:earring_left': palettes__004__jewelry,
      'pattern:earring_right': palettes__004__jewelry,
      'pattern:earrings2': palettes__004__jewelry,
      'pattern:earring2_left': palettes__004__jewelry,
      'pattern:earring2_right': palettes__004__jewelry,
      'pattern:chain_10mm': palettes__004__jewelry,
      'pattern:long_chain_10mm': palettes__004__jewelry,
      'pattern:chain_20mm': palettes__004__jewelry,
      'pattern:long_chain_20mm': palettes__004__jewelry,
      'pattern:medallion_chain': palettes__004__jewelry,
      'pattern:medallion_necklace': palettes__016__belts,
      'pattern:bracelets': palettes__004__jewelry,
      'pattern:bracelet_left': palettes__004__jewelry,
      'pattern:bracelet_right': palettes__004__jewelry,
    },
  },
  [AvatarLayerStack.makeup.name]: {
    layer: AvatarLayerStack.makeup,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:lipstick': palettes__015__makeup,
      'pattern:blush': palettes__015__makeup,
      'pattern:blush2': palettes__015__makeup,
      'pattern:eye_shadow_top': palettes__015__makeup,
      'pattern:eye_shadow_square': palettes__015__makeup,
      'pattern:lipstick_eye_shadow': palettes__015__makeup,
      'pattern:lipstick_blush': palettes__015__makeup,
      'pattern:lipstick_blush2': palettes__015__makeup,
      'pattern:lipstick_blush_eye_shadow': palettes__015__makeup,
      'pattern:lipstick_blush2_eye_shadow': palettes__015__makeup,
      // 'pattern:warpaint_arrow': palettes__016__makeup,
      'pattern:warpaint_vertical': palettes__015__makeup,
      'pattern:warpaint_horizontal': palettes__015__makeup,
      'pattern:warpaint_cross': palettes__015__makeup,
      'pattern:warpaint_x': palettes__015__makeup,
    },
  },
  [AvatarLayerStack.outerwear.name]: {
    layer: AvatarLayerStack.outerwear,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:belt': palettes__016__belts,
      'pattern:big_belt': palettes__016__belts,
      'pattern:tunic_strap': palettes__016__belts,
    },
  },
  [AvatarLayerStack.left_eye.name]: {
    layer: AvatarLayerStack.left_eye,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:square': palettes__005__eyes,
      'pattern:horizontal': palettes__005__eyes,
      'pattern:vertical': palettes__005__eyes,
      'pattern:terminator': palettes__001__themes,
      'pattern:cyborg': palettes__001__themes,
    },
  },
  [AvatarLayerStack.right_eye.name]: {
    layer: AvatarLayerStack.right_eye,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:square': palettes__005__eyes,
      'pattern:horizontal': palettes__005__eyes,
      'pattern:vertical': palettes__005__eyes,
      'pattern:terminator': palettes__001__themes,
      'pattern:cyborg': palettes__001__themes,
    },
  },
  [AvatarLayerStack.eyewear.name]: {
    layer: AvatarLayerStack.eyewear,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:glasses_tortoiseshell': palettes__013__glasses_tortoiseshell,
      'pattern:glasses_fullframe': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:glasses_halfframe': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:glasses_topframe': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:glasses_aviator': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:glasses_aviator2': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:glasses_rimless': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:glasses_3d': palettes__012__glasses_3d,
      'pattern:sunglasses_retro': palettes__011__sunglasses,
      'pattern:sunshield': palettes__008__sunshield,
      'pattern:sunshield_visor': palettes__008__sunshield,
      'pattern:face_shield': palettes__006__glasses_solid_with_clear_lenses,
      'pattern:ar_vr_visor': palettes__011__sunglasses,
      'pattern:vr': palettes__009__vr,
      'pattern:vr_rainbow': palettes__010__vr_rainbow,
      'pattern:led_ticker': palettes__001__themes,
      'pattern:led_ticker_left': palettes__001__themes,
      'pattern:led_ticker_right': palettes__001__themes,
      // 'pattern:eyescreen_left': palettes__012__eyescreen,
      // 'pattern:eyescreen_right': palettes__012__eyescreen,
      // 'pattern:eyescreenball_left': palettes__012__eyescreen,
      // 'pattern:eyescreenball_right': palettes__012__eyescreen,
      // 'pattern:eyescreenballs': palettes__012__eyescreen,
    },
  },
  [AvatarLayerStack.hair.name]: {
    layer: AvatarLayerStack.hair,
    patterns: {
      'pattern:bald': palettes__000__transparent,
      'pattern:buzzed': palettes__003__hair,
      'pattern:balding': palettes__003__hair,
      'pattern:mohawk': palettes__003__hair,
      // 'pattern:arrowhawk': palettes__003__hair,
      'pattern:skullet': palettes__003__hair,
      'pattern:long_balding': palettes__003__hair,
      'pattern:fade': palettes__003__hair,
      'pattern:short': palettes__003__hair,
      'pattern:widows_peak': palettes__003__hair,
      'pattern:side_part': palettes__003__hair,
      'pattern:slicked_back': palettes__003__hair,
      'pattern:fohawk': palettes__003__hair,
      'pattern:short_shaggy': palettes__003__hair,
      'pattern:floppy': palettes__003__hair,
      'pattern:shaggy': palettes__003__hair,
      'pattern:tousled': palettes__003__hair,
      'pattern:wild': palettes__003__hair,
      'pattern:spiky': palettes__003__hair,
      // 'pattern:ultra_spiky': palettes__003__hair,
      'pattern:dreads': palettes__003__hair,
      'pattern:pharaoh': palettes__003__hair,
      'pattern:long': palettes__003__hair,
      'pattern:long_straight': palettes__003__hair,
      'pattern:long_wavy': palettes__003__hair,
      'pattern:long_behind_ears': palettes__003__hair,
      'pattern:medium': palettes__003__hair,
      'pattern:pixie_cut': palettes__003__hair,
      'pattern:bob': palettes__003__hair,
      'pattern:long_bob': palettes__003__hair,
      'pattern:bowl': palettes__003__hair,
      'pattern:small_afro': palettes__003__hair,
      'pattern:afro': palettes__003__hair,
      'pattern:large_afro': palettes__003__hair,
    },
  },
  [AvatarLayerStack.handwear.name]: {
    layer: AvatarLayerStack.handwear,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:gloves1': palettes__001__themes,
      'pattern:gloves2': palettes__001__themes,
      'pattern:gloves3': palettes__001__themes,
      'pattern:gloves4': palettes__001__themes,
      'pattern:gloves5': palettes__001__themes,
      'pattern:gloves6': palettes__001__themes,
      'pattern:gloves7': palettes__001__themes,
    },
  },
  [AvatarLayerStack.tattoos.name]: {
    layer: AvatarLayerStack.tattoos,
    patterns: {
      'pattern:none': palettes__000__transparent,
      'pattern:teardrops': palettes__001__themes,
      'pattern:facetat': palettes__001__themes,
      // 'pattern:two_faced': palettes__001__themes,
      'pattern:armsleeves': palettes__001__themes,
      // 'pattern:plus': palettes__001__themes,
      // 'pattern:cross': palettes__001__themes,
      'pattern:crest': palettes__001__themes,
      'pattern:bird_wings': palettes__001__themes,
      'pattern:bodytat': palettes__001__themes,
      'pattern:bodytat2': palettes__001__themes,
      'pattern:bodystripes': palettes__001__themes,
      // 'pattern:checkerboard_body': palettes__001__themes,
      // 'pattern:checkerboard_head': palettes__004__colors_and_themes,
      // 'pattern:checkerboard_full': palettes__004__colors_and_themes,
    },
  },
  [AvatarLayerStack.topwear.name]: {
    layer: AvatarLayerStack.topwear,
    patterns: {
      'pattern:naked': palettes__000__transparent,
      'pattern:tshirt_solid1': palettes__001__themes,
      'pattern:tshirt_solid2': palettes__001__themes,
      'pattern:tshirt_solid3': palettes__001__themes,
      'pattern:tshirt_solid4': palettes__001__themes,
      'pattern:tshirt_solid5': palettes__001__themes,
      'pattern:tshirt_solid6': palettes__001__themes,
      'pattern:tshirt_solid7': palettes__001__themes,
      'pattern:tshirt_pocket1': palettes__001__themes,
      'pattern:tshirt_pocket2': palettes__001__themes,
      'pattern:tshirt_pocket3': palettes__001__themes,
      'pattern:tshirt_pocket4': palettes__001__themes,
      'pattern:tshirt_pocket5': palettes__001__themes,
      'pattern:tshirt_pocket6': palettes__001__themes,
      'pattern:tshirt_pocket7': palettes__001__themes,
      'pattern:tshirt_gradient1': palettes__001__themes,
      'pattern:tshirt_gradient2': palettes__001__themes,
      'pattern:tshirt_gradient3': palettes__001__themes,
      'pattern:tshirt_stripes1': palettes__001__themes,
      'pattern:tshirt_stripes2': palettes__001__themes,
      'pattern:tshirt_stripes3': palettes__001__themes,
      'pattern:tshirt_stripes4': palettes__001__themes,
      'pattern:tshirt_stripes5': palettes__001__themes,
      'pattern:tshirt_speckled1': palettes__001__themes,
      'pattern:tshirt_speckled2': palettes__001__themes,
      'pattern:tshirt_speckled3': palettes__001__themes,
      'pattern:tshirt_speckled4': palettes__001__themes,
      'pattern:vneck_solid1': palettes__001__themes,
      'pattern:vneck_solid2': palettes__001__themes,
      'pattern:vneck_solid3': palettes__001__themes,
      'pattern:vneck_solid4': palettes__001__themes,
      'pattern:vneck_solid5': palettes__001__themes,
      'pattern:vneck_solid6': palettes__001__themes,
      'pattern:vneck_solid7': palettes__001__themes,
      'pattern:vneck_gradient1': palettes__001__themes,
      'pattern:vneck_gradient2': palettes__001__themes,
      'pattern:vneck_gradient3': palettes__001__themes,
      'pattern:tanktop_solid1': palettes__001__themes,
      'pattern:tanktop_solid2': palettes__001__themes,
      'pattern:tanktop_solid3': palettes__001__themes,
      'pattern:tanktop_solid4': palettes__001__themes,
      'pattern:tanktop_solid5': palettes__001__themes,
      'pattern:tanktop_solid6': palettes__001__themes,
      'pattern:tanktop_solid7': palettes__001__themes,
      'pattern:tanktop_gradient1': palettes__001__themes,
      'pattern:tanktop_gradient2': palettes__001__themes,
      'pattern:tanktop_gradient3': palettes__001__themes,
      'pattern:croptop_gradient1': palettes__001__themes,
      'pattern:croptop_gradient2': palettes__001__themes,
      'pattern:croptop_gradient3': palettes__001__themes,
      'pattern:croptop_gradient4': palettes__001__themes,
      'pattern:croptop_gradient5': palettes__001__themes,
      'pattern:croptop_gradient6': palettes__001__themes,
      'pattern:bra_solid1': palettes__001__themes,
      'pattern:bra_solid2': palettes__001__themes,
      'pattern:bra_solid3': palettes__001__themes,
      'pattern:bra_solid4': palettes__001__themes,
      'pattern:bra_solid5': palettes__001__themes,
      'pattern:bra_solid6': palettes__001__themes,
      'pattern:bra_solid7': palettes__001__themes,
      'pattern:bra_gradient1': palettes__001__themes,
      'pattern:bra_gradient2': palettes__001__themes,
      'pattern:bra_gradient3': palettes__001__themes,
      'pattern:bra_gradient4': palettes__001__themes,
      'pattern:sports_bra_solid1': palettes__001__themes,
      'pattern:sports_bra_solid2': palettes__001__themes,
      'pattern:sports_bra_solid3': palettes__001__themes,
      'pattern:sports_bra_solid4': palettes__001__themes,
      'pattern:sports_bra_solid5': palettes__001__themes,
      'pattern:sports_bra_solid6': palettes__001__themes,
      'pattern:sports_bra_solid7': palettes__001__themes,
      'pattern:sports_bra_gradient1': palettes__001__themes,
      'pattern:sports_bra_gradient2': palettes__001__themes,
      'pattern:sports_bra_gradient3': palettes__001__themes,
      'pattern:sports_bra_gradient4': palettes__001__themes,
      'pattern:dress_lowcut_gradient1': palettes__001__themes,
      'pattern:dress_lowcut_gradient2': palettes__001__themes,
      'pattern:dress_gradient1': palettes__001__themes,
      'pattern:dress_gradient2': palettes__001__themes,
      'pattern:space_suit': palettes__007__space_suit,
      'pattern:space_shirt': palettes__007__space_suit,
      'pattern:space_tank': palettes__007__space_suit,
      // 'pattern:trenchcoat': palettes__018__top__trenchcoat,
    },
  },
}
