import { PaletteConfig } from 'src/core/Config'
import { PaletteCode } from './PaletteCode'

export class PaletteList {
  public static THEMES: string[] = [
    'theme__001__black',
    'theme__002__dark_gray',
    'theme__003__gray',
    'theme__004__light_gray',
    'theme__005__white',
    'theme__006__fuchsia',
    'theme__007__radiant_rose',
    'theme__008__magenta',
    'theme__009__violet',
    'theme__010__soft_pink',
    'theme__011__punk_pop',
    'theme__012__pink_purple',
    'theme__013__hot_pink',
    'theme__014__violet_plum',
    'theme__015__lavender_dusk',
    'theme__016__mountain_dawn',
    'theme__017__velvet',
    'theme__018__pastel_daydream',
    'theme__019__cherry_blossom',
    'theme__020__sakura_spring',
    'theme__021__maroon',
    'theme__022__spring_blossom',
    'theme__023__scarlet_red',
    'theme__024__pink',
    'theme__025__cherry_red',
    'theme__026__sunset',
    'theme__027__red',
    'theme__028__blood_red',
    'theme__029__crimson',
    'theme__030__maraschino_cherry_red',
    'theme__031__dragon_red',
    'theme__032__desert_dream',
    'theme__033__blush_spectrum',
    'theme__034__salmon',
    'theme__035__coral',
    'theme__036__fire_and_ice',
    'theme__037__red_blaze',
    'theme__038__desert_sunset',
    'theme__039__hippy_harmony',
    'theme__040__peach',
    'theme__041__sunrise',
    'theme__042__tropical_punch',
    'theme__043__orange_tangerine',
    'theme__044__orange_peach',
    'theme__045__desert_orange',
    'theme__046__orange_apricot',
    'theme__047__emberglow',
    'theme__048__autumn_glow',
    'theme__049__light_brown',
    'theme__050__desert_dusk',
    'theme__051__pastel_paradise',
    'theme__052__autumn_leaves',
    'theme__053__desert_oasis',
    'theme__054__orange',
    'theme__055__carrot_orange',
    'theme__056__warm_glow',
    'theme__057__sunbaked_timber',
    'theme__058__rainforest_canopy',
    'theme__059__yellow_golden',
    'theme__060__golden_harvest',
    'theme__061__autumn_serenade',
    'theme__062__gold',
    'theme__063__yellow_canary',
    'theme__064__yellow',
    'theme__065__yellow_lemon',
    'theme__066__jungle_canopy',
    'theme__067__aurora_tides',
    'theme__068__yellow_blood',
    'theme__069__summer_solstice',
    'theme__070__green_olive',
    'theme__071__green_chartreuse',
    'theme__072__thunder',
    'theme__073__lime_yellow',
    'theme__074__forest',
    'theme__075__green_kelly',
    'theme__076__green_lime',
    'theme__077__green_forest',
    'theme__078__green_hunter',
    'theme__079__green',
    'theme__080__green_blood',
    'theme__081__green_sage',
    'theme__082__earth_and_sky',
    'theme__083__enchanted_forest',
    'theme__084__luminescent_lagoon',
    'theme__085__rainforest_rhapsody',
    'theme__086__light_green',
    'theme__087__green_jade',
    'theme__088__evergreen',
    'theme__089__emerald_dream',
    'theme__090__caribbean_beach',
    'theme__091__green_mint',
    'theme__092__green_emerald',
    'theme__093__seafoam',
    'theme__094__aquamarine',
    'theme__095__blue_teal',
    'theme__096__cool_green',
    'theme__097__cybershock',
    'theme__098__mint_breeze',
    'theme__099__tropical_twighlight',
    'theme__100__cyan_blood',
    'theme__101__teal',
    'theme__102__diamond',
    'theme__103__cyan',
    'theme__104__blue_aquamarine',
    'theme__105__electric_rain',
    'theme__106__turquoise',
    'theme__107__ocean_depths',
    'theme__108__cyberpunk',
    'theme__109__blue_cyan',
    'theme__110__blue_green',
    'theme__111__ocean_sunset',
    'theme__112__blue_sky',
    'theme__113__azure_escape',
    'theme__114__cybercandy',
    'theme__115__blue_sea',
    'theme__116__marine_blue',
    'theme__117__coastal_waters',
    'theme__118__arctic_aurora',
    'theme__119__blue',
    'theme__120__blue_slateblue',
    'theme__121__coral_reef',
    'theme__122__winter_whispers',
    'theme__123__celestial_haze',
    'theme__124__blue_denim',
    'theme__125__blue_navy',
    'theme__126__indigo',
    'theme__127__deep_indigo',
    'theme__128__evening_frost',
    'theme__129__silver',
    'theme__130__periwinkle',
    'theme__131__indigo_bright',
    'theme__132__midnight_dream',
    'theme__133__cotton_candy',
    'theme__134__lilac',
    'theme__135__deep_violet',
    'theme__136__grape',
    'theme__137__violet_blue',
    'theme__138__lavender',
    'theme__139__purple_nightshade',
    'theme__140__dark_violet',
    'theme__141__galactic_burst',
    'theme__142__mystical_midnight',
    'theme__143__cyberpink',
    'theme__144__mystic_lavender',
    'theme__145__midnight_amethyst',
    'theme__146__electric_shock',
    'theme__147__muave',
    'theme__148__purple',
    'theme__149__cybercotton',
    'theme__150__retro_neon',
  ]

  public static NATURAL_HAIR: string[] = [
    'natural_black',
    'natural_near_black',
    'natural_very_dark_gray',
    'natural_dark_gray',
    'natural_speckled_gray',
    'natural_medium_dark_gray',
    'natural_medium_gray',
    'natural_light_medium_gray',
    'natural_light_gray',
    'natural_near_white',
    'natural_darkest_brown',
    'natural_darker_brown',
    'natural_dark_brown',
    'natural_brown',
    'natural_light_brown',
    'natural_lighter_brown',
    'natural_lightest_brown',
    'natural_dark_blonde',
    'natural_dirty_blonde',
    'natural_light_blonde',
    'natural_blonde',
    'natural_bright_blonde',
    'natural_bleach_blonde',
    'natural_platinum_blonde',
    'natural_strawberry_blonde',
    'natural_mahogony_red',
    'natural_auburn_red',
    'natural_redhead',
    'natural_rustic_red',
    'natural_ginger_snap',
    'natural_copper_red',
  ]

  public static GREEK_DEITIES: string[] = [
    'greek_diety_zeus',
    'greek_diety_hera',
    'greek_diety_poseidon',
    'greek_diety_athena',
    'greek_diety_apollo',
    'greek_diety_artemis',
    'greek_diety_ares',
    'greek_diety_aphrodite',
    'greek_diety_haides',
    'greek_diety_persephone',
  ]

  public static ALIENS: string[] = [
    'alien_gray',
    'alien_zeta_reticulan',
    'alien_pale_blue',
    'alien_blue',
    'alien_martian_pale',
    'alien_martian_medium',
    'alien_martian_dark',
    'alien_martian_metallic',
    'alien_blue_gray',
    'alien_cryptopunks',
    'alien_gray_green',
    'alien_roswell',
  ]
  public static DEMONS: string[] = [
    'demon_shadow',
    'demon_succubus',
    'demon_incubus',
    'demon_inferno',
    'demon_flesh',
    'demon_ice',
    'demon_acid',
    'demon_undead',
    'demon_fire',
    'demon_volcano',
    'demon_hellfire',
  ]

  public static ZOMBIES: string[] = [
    'zombie_cryptopunks',
    'zombie_radioactive',
    'zombie_infected',
    'zombie_festering',
    'zombie_rotten',
  ]
  public static GHOSTS: string[] = ['ghost_white', 'ghost_misty', 'ghost_gray', 'ghost_shadow']
  public static VOIDS: string[] = ['void_light', 'void_dark', 'void_near_black', 'void_black']
  public static GENIES: string[] = [
    'genie_blue',
    'genie_mystical',
    'genie_jinn',
    'genie_ifrit',
    'genie_marid',
    'genie_shaitan',
    'genie_ghul',
  ]

  public static OGRES: string[] = [
    'ogre_desert',
    'ogre_mountain',
    'ogre_swamp',
    'ogre_glade',
    'ogre_forest',
    'ogre_volcano',
  ]
  public static TROLLS: string[] = [
    'troll_cave_dweller',
    'troll_mountain_wanderer',
    'troll_dune_walker',
    'troll_azure_warrior',
    'troll_forest_guardian',
  ]

  public static METALS: string[] = [
    'metal_platinum',
    'metal_gold',
    'metal_alloy_rose_gold',
    'metal_titanium',
    'metal_titanium_black',
    'metal_titanium_blue',
    'metal_titanium_white',
    'metal_tungsten',
    'metal_cobalt',
    'metal_silver',
    'metal_alloy_bronze_gold',
    'metal_alloy_stainless_steel',
    'metal_alloy_pewter',
    'metal_alloy_bronze',
    'metal_alloy_brass',
    'metal_nickel',
    'metal_chromium',
    'metal_copper',
    'metal_iron',
    'metal_aluminum',
  ]

  public static CRYSTALS: string[] = [
    'crystal_diamond',
    'crystal_ruby',
    'crystal_sapphire',
    'crystal_emerald',
    'crystal_jade',
    'crystal_topaz',
    'crystal_opal',
    'crystal_citrine',
    'crystal_amethyst',
    'crystal_lapis_lazuli',
    'crystal_peridot',
    'crystal_quartz',
    'crystal_obsidian',
    'crystal_garnet',
    'crystal_turquoise',
    'crystal_moonstone',
    'crystal_aquamarine',
    'crystal_tanzanite',
    'crystal_morganite',
  ]

  public static CARBONS: string[] = [
    'carbon_graphite',
    'carbon_nanotubes',
    'carbon_fullerenes',
    'carbon_amorphous',
    'carbon_glassy',
    'carbon_fiber',
    'carbon_lonsdaleite',
  ]

  public static CERAMICS: string[] = [
    'ceramic_porcelain',
    'ceramic_stoneware',
    'ceramic_terracota',
    'ceramic_earthenware',
  ]

  public static PLASTICS: string[] = [
    'plastic_polyethylene',
    'plastic_polypropylene',
    'plastic_polyvinyl_chloride',
    'plastic_polystyrene',
    'plastic_polyethylene_terephthalate',
  ]

  public static RUBBERS: string[] = ['rubber_silicon', 'rubber_natural', 'rubber_nitrile', 'rubber_neoprene']

  public static WOODS: string[] = [
    'wood_ebony',
    'wood_wenge',
    'wood_rosewood',
    'wood_walnut',
    'wood_mahogany',
    'wood_cherry',
    'wood_teak',
    'wood_oak',
    'wood_maple',
    'wood_bamboo',
    'wood_pine',
    'wood_birch',
  ]
}

export const palettes__000__transparent: PaletteConfig = {
  code: PaletteCode.TRANSPARENT,
  palettes: ['transparent'],
}

export const palettes__001__themes: PaletteConfig = {
  code: PaletteCode.THEMES,
  palettes: [...PaletteList.THEMES],
}

export const palettes__002__humanoid_human: PaletteConfig = {
  code: PaletteCode.HUMANOID_HUMAN,
  palettes: [
    ...Array.from({ length: 100 }, (_, i) => `human${(i + 1).toString().padStart(3, '0')}`),
    ...Array.from({ length: 5 }, (_, i) => `sunburn${(i + 1).toString()}`),
  ],
}

export const palettes__003__hair: PaletteConfig = {
  code: PaletteCode.HAIR,
  palettes: [...PaletteList.THEMES, ...PaletteList.NATURAL_HAIR],
}

const jewelryPalettes = [
  'crystal_diamond',
  'metal_gold',
  'metal_silver',
  'metal_platinum',
  'crystal_ruby',
  'crystal_sapphire',
  'crystal_emerald',

  'crystal_amethyst',
  'crystal_aquamarine',
  'crystal_lapis_lazuli',
  'crystal_turquoise',
  'crystal_tanzanite',
  'crystal_morganite',
  'crystal_topaz',
  'crystal_citrine',
  'crystal_peridot',
  'crystal_garnet',

  'crystal_opal',
  'crystal_jade',
  'crystal_moonstone',
  'crystal_quartz',

  'crystal_obsidian',

  'metal_titanium',
  'metal_alloy_stainless_steel',
  'metal_alloy_bronze',
  'metal_iron',
  'metal_aluminum',
  'metal_copper',
  'metal_nickel',
  'metal_chromium',
  'metal_tungsten',
  'metal_cobalt',

  'metal_titanium_black',
  'metal_titanium_blue',
  'metal_titanium_white',
  'metal_alloy_rose_gold',
  'metal_alloy_bronze_gold',
  'metal_alloy_brass',
  'metal_alloy_pewter',
]

function validateUnion(list: string[], ...subLists: string[][]): boolean {
  const combinedSubLists: string[] = ([] as string[]).concat(...subLists)
  if (list.length !== combinedSubLists.length) {
    return false
  }
  for (const item of list) {
    if (!combinedSubLists.includes(item)) {
      return false
    }
  }
  return true
}

const isValid = validateUnion(jewelryPalettes, PaletteList.CRYSTALS, PaletteList.METALS)
if (!isValid) {
  throw new Error('jewelryPalettes is not a valid union of sub-lists')
}

export const palettes__004__jewelry: PaletteConfig = {
  code: PaletteCode.JEWELRY,
  palettes: jewelryPalettes,
}

export const palettes__005__eyes: PaletteConfig = {
  code: 5,
  palettes: [
    'black',
    'gray1',
    'gray2',
    'gray3',
    'brown1',
    'brown2',
    'brown3',
    'brown4',
    'brown5',
    'brown6',
    'hazel1',
    'hazel2',
    'hazel3',
    'red1',
    'red2',
    'red3',
    'rose_gold1',
    'rose_gold2',
    'rose_gold3',
    'coral1',
    'coral2',
    'coral3',
    'orange1',
    'orange2',
    'orange3',
    'amber1',
    'amber2',
    'amber3',
    'yellow1',
    'yellow2',
    'yellow3',
    'green1',
    'green2',
    'green3',
    'green4',
    'green5',
    'green6',
    'green7',
    'green_gray1',
    'green_gray2',
    'green_gray3',
    'blue_green1',
    'blue_green2',
    'blue_green3',
    'teal1',
    'teal2',
    'teal3',
    'blue_gray1',
    'blue_gray2',
    'blue_gray3',
    'cyan1',
    'cyan2',
    'cyan3',
    'turquoise1',
    'turquoise2',
    'turquoise3',
    'blue1',
    'blue2',
    'blue3',
    'blue4',
    'blue5',
    'blue6',
    'blue7',
    'periwinkle1',
    'periwinkle2',
    'periwinkle3',
    'lavender1',
    'lavender2',
    'lavender3',
    'violet1',
    'violet2',
    'violet3',
    'magenta1',
    'magenta2',
    'magenta3',
    'fuchsia1',
    'fuchsia2',
    'fuchsia3',
    'pink1',
    'pink2',
    'pink3',
    'special_pure_black',
    'special_pure_white',
    'special_crosseye',
    'special_glazed',
    'special_hazy',
    'special_bloodshot',
    'special_jaundice',
    'special_mystic',
    'special_glisten',
    'special_teary',
    'special_blackeye',
    'special_hypnotic',
  ],
}

export const palettes__006__glasses_solid_with_clear_lenses: PaletteConfig = {
  code: PaletteCode.GLASSES_SOLID_WITH_CLEAR_LENSES,
  palettes: [
    'black',
    'quarter_transluscent_black',
    'semi_transluscent_black',
    'transluscent_black',
    'silver',
    'white',
    'quarter_transluscent_white',
    'semi_transluscent_white',
    'transluscent_white',
    'semi_transluscent_blue_gray',
    'transluscent_blue_gray',
    'gold',
  ],
}

export const palettes__007__space_suit: PaletteConfig = {
  code: PaletteCode.SPACE_SUIT,
  palettes: [
    'light',
    'dark',
    'diamond',
    'gold',
    'silver',
    'black_hole',
    'milky_way',
    'sun',
    'mercury',
    'venus',
    'earth',
    'mars',
    'asteroid_belt',
    'jupiter',
    'saturn',
    'uranus',
    'neptune',
    'kuiper_belt',
    'pluto',
    'planet_nine',
    'cosmic_void',
    'supernova',
    'quasar',
    'cyberpunk',
    'tech_blue',
    'cybernetic',
    'military_green',
    'alien_green',
    'matrix',
    'red_dwarf',
    'red_orange',
    'red',
    'pink',
    'yellow',
    'lime',
    'green',
    'teal',
    'cyan',
    'blue',
    'purple',
  ],
}

export const palettes__008__sunshield: PaletteConfig = {
  code: PaletteCode.SUNSHIELD,
  palettes: ['sun_reflection'],
}

export const palettes__009__vr: PaletteConfig = {
  code: PaletteCode.VR,
  palettes: ['black', 'gray', 'offwhite', 'diamond', 'gold', 'silver'],
}

export const palettes__010__vr_rainbow: PaletteConfig = {
  code: PaletteCode.VR_RAINBOW,
  palettes: ['rainbow_black', 'rainbow_diamond', 'rainbow_gold', 'rainbow_silver'],
}
export const palettes__011__sunglasses: PaletteConfig = {
  code: PaletteCode.SUNGLASSES,
  palettes: [
    'diamond',
    'gold',
    'silver',
    'fuchsia',
    'magenta',
    'violet',
    'pink',
    'coral',
    'red',
    'orange',
    'yellow',
    'lime',
    'green',
    'turquoise',
    'teal',
    'cyan',
    'blue',
    'indigo',
    'purple',
    'lavender',
  ].flatMap((color) => ['', 'semi_transluscent_', 'transluscent_'].map((prefix) => prefix + color)),
}

export const palettes__012__glasses_3d: PaletteConfig = {
  code: PaletteCode.FACE__GLASSES_3D,
  palettes: ['black', 'silver', 'white'],
}

export const palettes__013__glasses_tortoiseshell: PaletteConfig = {
  code: PaletteCode.FACE__GLASSES_TORTOISESHELL,
  palettes: ['red', 'green', 'blue'],
}

export const palettes__014__medical_mask: PaletteConfig = {
  code: PaletteCode.FACE__MEDICAL_MASK,
  palettes: ['black', 'blue', 'pink', 'white'],
}
export const palettes__015__makeup: PaletteConfig = {
  code: PaletteCode.MAKEUP,
  palettes: [
    'brown',
    'beige',
    'gold',
    'silver',
    'bronze',
    'red',
    'pink',
    'coral',
    'orange',
    'yellow',
    'green',
    'cyan',
    'blue',
    'purple',
    'lavender',
    'magenta',
    'black',
    'white',
  ].flatMap((color) => ['natural_', 'subtle_', '', 'glam_'].map((prefix) => prefix + color)),
}

export const palettes__016__belts: PaletteConfig = {
  code: PaletteCode.BELTS,
  palettes: ['black', 'brown', 'gray', 'iron', 'white'].flatMap((primary) =>
    ['black', 'gold', 'silver', 'platinum', 'diamond'].map((accent) => primary + '_' + accent)
  ),
}

// export const palettes__017__eyescreen: PaletteConfig = {
//   code: PaletteCode.EYESCREEN,
//   palettes: [
//     'magenta',
//     'red',
//     'orange',
//     // 'yellow',
//     'green',
//     'cyan',
//     'windows_blue',
//     // 'blue',
//     'purple',
//   ],
// }

// export const palettes__018__rainbow: PaletteConfig = {
//   code: PaletteCode.RAINBOW,
//   palettes: ['rainbow', 'rainbow_titanium'],
// }

// export const palettes__021__humanoid_placeholder: PaletteConfig = {
//   code: PaletteCode.HUMANOID_PLACEHOLDER,
//   palettes: [
//     ...PaletteList.GREEK_DEITIES,
//     ...PaletteList.ALIENS,
//     ...PaletteList.DEMONS,
//     ...PaletteList.ZOMBIES,
//     ...PaletteList.GHOSTS,
//     ...PaletteList.VOIDS,
//     ...PaletteList.GENIES,
//     ...PaletteList.OGRES,
//     ...PaletteList.TROLLS,

//     // TODO cyanotype from PS
//     ...PaletteList.METALS,
//     ...PaletteList.CRYSTALS,
//     ...PaletteList.CARBONS,
//     ...PaletteList.CERAMICS,
//     ...PaletteList.PLASTICS,
//     ...PaletteList.RUBBERS,
//     ...PaletteList.WOODS,
//   ],
// }

// export const palettes__022__humanoid_geographic: PaletteConfig = {
//   code: PaletteCode.HUMANOID_GEOGRAPHIC,
//   palettes: [
//     'skin0',
//     'skin1',
//     'skin2',
//     'skin3',
//     'skin4',
//     'skin5',
//     'skin6',
//     'skin7',
//     'skin8',
//     'skin9',

//     'summer_tan0',
//     'summer_tan1',
//     'summer_tan2',
//     'summer_tan3',
//     'summer_tan4',

//     'sunburn0',
//     'sunburn1',
//     'sunburn2',
//     'sunburn3',
//     'sunburn4',

//     'albinism0',
//     'albinism1',
//     'albinism2',
//     'albinism3',
//     'albinism4',

//     'european0',
//     'european1',
//     'european2',
//     'european3',
//     'european4',

//     'east_asian0',
//     'east_asian1',
//     'east_asian2',
//     'east_asian3',
//     'east_asian4',

//     'south_asian0',
//     'south_asian1',
//     'south_asian2',
//     'south_asian3',
//     'south_asian4',

//     'southeast_asian0',
//     'southeast_asian1',
//     'southeast_asian2',
//     'southeast_asian3',
//     'southeast_asian4',

//     'central_asian0',
//     'central_asian1',
//     'central_asian2',
//     'central_asian3',
//     'central_asian4',

//     'middle_eastern0',
//     'middle_eastern1',
//     'middle_eastern2',
//     'middle_eastern3',
//     'middle_eastern4',

//     'african0',
//     'african1',
//     'african2',
//     'african3',
//     'african4',

//     'north_african0',
//     'north_african1',
//     'north_african2',
//     'north_african3',
//     'north_african4',

//     'west_african0',
//     'west_african1',
//     'west_african2',
//     'west_african3',
//     'west_african4',

//     'east_african0',
//     'east_african1',
//     'east_african2',
//     'east_african3',
//     'east_african4',

//     'south_african0',
//     'south_african1',
//     'south_african2',
//     'south_african3',
//     'south_african4',

//     'indigenous_american0',
//     'indigenous_american1',
//     'indigenous_american2',
//     'indigenous_american3',
//     'indigenous_american4',

//     'hispanic0',
//     'hispanic1',
//     'hispanic2',
//     'hispanic3',
//     'hispanic4',

//     'pacific_islander0',
//     'pacific_islander1',
//     'pacific_islander2',
//     'pacific_islander3',
//     'pacific_islander4',

//     'aboriginal_australian0',
//     'aboriginal_australian1',
//     'aboriginal_australian2',
//     'aboriginal_australian3',
//     'aboriginal_australian4',

//     'mixed0',
//     'mixed1',
//     'mixed2',
//     'mixed3',
//     'mixed4',
//   ],
// }
